sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jsgr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jsgr/react-test npm test

after_success:
  - docker build -t jsgr/multi-app-client ./client
  - docker build -t jsgr/multi-app-nginx ./nginx
  - docker build -t jsgr/multi-app-server ./server
  - docker build -t jsgr/multi-app-worker ./worker
  # login into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stin
  #take those images and push them to docker hub
  - docker push jsebastiang/multi-app-client ./client
  - docker push jsebastiang/multi-app-nginx ./nginx
  - docker push jsebastiang/multi-app-server ./server
  - docker push jsebastiang/multi-app-worker ./worker

