sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jsebastiang/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jsebastiang/react-test npm test

after_success:
  - docker build -t jsebastiang/multi-app-client ./client
  - docker build -t jsebastiang/multi-app-nginx ./nginx
  - docker build -t jsebastiang/multi-app-server ./server
  - docker build -t jsebastiang/multi-app-worker ./worker
  # login into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push jsebastiang/multi-app-client
  - docker push jsebastiang/multi-app-nginx
  - docker push jsebastiang/multi-app-server
  - docker push jsebastiang/multi-app-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-container-app"
  env: "Multicontainerapp-env"
  bucket_name: "elasticbeanstalk-eu-west-1-136824170700"
  bucket_path: "docker-multi"
  on:
    branch: "master"
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"